"""initial migration

Revision ID: 082c22dd8174
Revises: 
Create Date: 2024-04-18 11:57:24.213570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082c22dd8174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('profile_img', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('closed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Enum('BUY', 'SELL', name='position_type'), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_trades')
    op.drop_table('closed_trades')
    op.drop_table('users')
    # ### end Alembic commands ###
