"""changed lot to float

Revision ID: 952d81fb61ae
Revises: 9cba8109499f
Create Date: 2024-04-25 13:02:37.170470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952d81fb61ae'
down_revision = '9cba8109499f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_trades', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('open_trades', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_trades', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('closed_trades', schema=None) as batch_op:
        batch_op.alter_column('lot',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
