"""Initial migration

Revision ID: c52653afd79c
Revises: 
Create Date: 2024-05-09 11:13:34.216855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52653afd79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('capital', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('profile_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('closed_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('mp', sa.Float(), nullable=True),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Enum('BUY', 'SELL', name='position_type'), nullable=True),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.Column('ep', sa.Integer(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('mp', sa.Float(), nullable=True),
    sa.Column('lot', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_trades')
    op.drop_table('closed_trades')
    op.drop_table('users')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
