"""Changed nullable values

Revision ID: d77db296f8ae
Revises: 9453eeb638de
Create Date: 2024-04-18 10:26:11.695312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77db296f8ae'
down_revision = '9453eeb638de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_trades', schema=None) as batch_op:
        batch_op.alter_column('tp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sl',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_trades', schema=None) as batch_op:
        batch_op.alter_column('sl',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('tp',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
